name: 🤖 Sync mit Authentik upstream
on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dein Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git-User konfigurieren
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Upstream-Remote konfigurieren
        run: |
          if git remote | grep -q upstream; then
            git remote remove upstream
          fi
          git remote add upstream https://github.com/goauthentik/authentik.git

      - name: Upstream holen & mergen
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit

      - name: Push in dein privates Repo
        run: |
          git push origin main
