name: 🤖 Sync mit Authentik upstream
on:
  schedule:
    - cron: '0 3 * * *'  # jeden Tag um 03:00 UTC (05:00 Europe/Vienna)
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dein Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upstream remote hinzufügen
        run: git remote add upstream https://github.com/goauthentik/authentik.git
      - name: Upstream holen & mergen
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
      - name: Push in dein privates Repo
        run: git push origin main
